// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chat.proto

package agrim_io

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfirmationResponse struct {
	Sent                 bool     `protobuf:"varint,1,opt,name=sent,proto3" json:"sent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmationResponse) Reset()         { *m = ConfirmationResponse{} }
func (m *ConfirmationResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmationResponse) ProtoMessage()    {}
func (*ConfirmationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{0}
}

func (m *ConfirmationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmationResponse.Unmarshal(m, b)
}
func (m *ConfirmationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmationResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmationResponse.Merge(m, src)
}
func (m *ConfirmationResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmationResponse.Size(m)
}
func (m *ConfirmationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmationResponse proto.InternalMessageInfo

func (m *ConfirmationResponse) GetSent() bool {
	if m != nil {
		return m.Sent
	}
	return false
}

type GetMessagesRequest struct {
	Reciever             string   `protobuf:"bytes,1,opt,name=reciever,proto3" json:"reciever,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{1}
}

func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (m *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(m, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

func (m *GetMessagesRequest) GetReciever() string {
	if m != nil {
		return m.Reciever
	}
	return ""
}

type GetMessagesResponse struct {
	Msg                  []*Messages `protobuf:"bytes,1,rep,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetMessagesResponse) Reset()         { *m = GetMessagesResponse{} }
func (m *GetMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponse) ProtoMessage()    {}
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{2}
}

func (m *GetMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponse.Unmarshal(m, b)
}
func (m *GetMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponse.Marshal(b, m, deterministic)
}
func (m *GetMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponse.Merge(m, src)
}
func (m *GetMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponse.Size(m)
}
func (m *GetMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponse proto.InternalMessageInfo

func (m *GetMessagesResponse) GetMsg() []*Messages {
	if m != nil {
		return m.Msg
	}
	return nil
}

type Messages struct {
	Sender               string   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reciever             string   `protobuf:"bytes,3,opt,name=reciever,proto3" json:"reciever,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c585a45e2093e54, []int{3}
}

func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (m *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(m, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *Messages) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Messages) GetReciever() string {
	if m != nil {
		return m.Reciever
	}
	return ""
}

func init() {
	proto.RegisterType((*ConfirmationResponse)(nil), "agrim.io.ConfirmationResponse")
	proto.RegisterType((*GetMessagesRequest)(nil), "agrim.io.GetMessagesRequest")
	proto.RegisterType((*GetMessagesResponse)(nil), "agrim.io.GetMessagesResponse")
	proto.RegisterType((*Messages)(nil), "agrim.io.messages")
}

func init() { proto.RegisterFile("chat.proto", fileDescriptor_8c585a45e2093e54) }

var fileDescriptor_8c585a45e2093e54 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0x41, 0x25, 0x5c, 0xb6, 0x03, 0xa1, 0x28, 0x02, 0x54, 0x59, 0x0c, 0x15, 0x43,
	0x84, 0xca, 0xc8, 0x98, 0x81, 0x05, 0x96, 0x74, 0x61, 0x35, 0xe9, 0x91, 0x7a, 0xb0, 0x5d, 0x7c,
	0xa6, 0xbf, 0x87, 0x9f, 0x8a, 0xb0, 0xec, 0x96, 0x88, 0xb0, 0xf9, 0xdd, 0x7b, 0x77, 0xfe, 0x7c,
	0x06, 0xe8, 0x37, 0xd2, 0x37, 0x5b, 0x67, 0xbd, 0xc5, 0x42, 0x0e, 0x4e, 0xe9, 0x46, 0x59, 0x71,
	0x07, 0x17, 0xad, 0x35, 0xef, 0xca, 0x69, 0xe9, 0x95, 0x35, 0x1d, 0xf1, 0xd6, 0x1a, 0x26, 0x44,
	0x38, 0x61, 0x32, 0xbe, 0xca, 0xe6, 0xd9, 0xa2, 0xe8, 0xc2, 0x59, 0xdc, 0x03, 0x3e, 0x91, 0x7f,
	0x21, 0x66, 0x39, 0x10, 0x77, 0xf4, 0xf1, 0x49, 0xec, 0xb1, 0x86, 0xc2, 0x51, 0xaf, 0x68, 0x47,
	0x2e, 0xa4, 0xcf, 0xba, 0xbd, 0x16, 0x8f, 0x70, 0x3e, 0xea, 0x88, 0xc3, 0x6f, 0x21, 0xd7, 0x3c,
	0x54, 0xd9, 0x3c, 0x5f, 0x94, 0x4b, 0x6c, 0x12, 0x4c, 0xa3, 0x53, 0xf0, 0xc7, 0x16, 0xaf, 0x50,
	0xa4, 0x02, 0x5e, 0xc2, 0x8c, 0xc9, 0xac, 0xf7, 0x57, 0x44, 0x85, 0x15, 0x9c, 0xc6, 0x4c, 0x75,
	0x1c, 0x8c, 0x24, 0x47, 0x58, 0xf9, 0x18, 0x6b, 0xf9, 0x95, 0x41, 0xd9, 0x6e, 0xa4, 0x5f, 0x91,
	0xdb, 0xa9, 0x9e, 0xb0, 0x85, 0x72, 0x45, 0x66, 0x1d, 0x39, 0x71, 0x82, 0xa8, 0xbe, 0x39, 0xd4,
	0xa6, 0xf6, 0x25, 0x8e, 0xf0, 0x19, 0xca, 0x5f, 0x6f, 0xc5, 0xab, 0x43, 0xc3, 0xdf, 0xa5, 0xd5,
	0xd7, 0xff, 0xb8, 0x69, 0xda, 0xdb, 0x2c, 0x7c, 0xd4, 0xc3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x58, 0xb3, 0x8b, 0x02, 0xb6, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	SendMessage(ctx context.Context, in *Messages, opts ...grpc.CallOption) (*ConfirmationResponse, error)
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) SendMessage(ctx context.Context, in *Messages, opts ...grpc.CallOption) (*ConfirmationResponse, error) {
	out := new(ConfirmationResponse)
	err := c.cc.Invoke(ctx, "/agrim.io.ChatService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	out := new(GetMessagesResponse)
	err := c.cc.Invoke(ctx, "/agrim.io.ChatService/GetMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	SendMessage(context.Context, *Messages) (*ConfirmationResponse, error)
	GetMessages(context.Context, *GetMessagesRequest) (*GetMessagesResponse, error)
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Messages)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agrim.io.ChatService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SendMessage(ctx, req.(*Messages))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agrim.io.ChatService/GetMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessages(ctx, req.(*GetMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agrim.io.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _ChatService_SendMessage_Handler,
		},
		{
			MethodName: "GetMessages",
			Handler:    _ChatService_GetMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
